/**
 * `noma init <dir> --template docs-repo`: a living knowledge base agents maintain
 * with proof-before-merge. Mirrors github.com/ferax564/noma-docs-template (MIT);
 * the GitHub Action and CLI are pinned to the running CLI version.
 */

const PIN = "__NOMA_VERSION__";

const FILES: Record<string, string> = {
  "docs/project.noma": "---\ntitle: Project Knowledge Base\nowner: your-team\nstatus: living\n---\n\n# Project Knowledge Base\n\nThis document is maintained by humans **and** AI agents. Every block below has a\nstable ID. Agents edit by submitting block-level patch operations — never by\nrewriting the file — and CI proves every patch is safe before it merges.\n\n## Overview {id=\"overview\"}\n\nDescribe what this project does, for whom, and why it exists. Keep this section\ncurrent: the freshness check in CI will flag it when it goes stale.\n\n::callout{id=\"how-to-edit\" variant=\"info\"}\n**Agents:** list block IDs with `noma ids docs/project.noma`, then submit patch\nops against those IDs. See `AGENTS.md` in the repo root for the full protocol.\n::\n\n## Architecture {id=\"architecture\"}\n\nSummarize the system's moving parts here.\n\n::table{id=\"components\" align=\"l,l,l\"}\n| Component | Responsibility | Owner |\n| api | Serves the public REST surface | @you |\n| worker | Background jobs and scheduled syncs | @you |\n::\n\n## Decisions {id=\"decisions\"}\n\n::decision{id=\"decision-0001\" status=\"accepted\" date=\"2026-06-10\"}\nUse Noma for this knowledge base so agents can patch individual blocks with\nproof-before-apply instead of rewriting whole files.\n::\n\n## Claims and Evidence {id=\"claims\"}\n\n::claim{id=\"claim-docs-drift\" confidence=0.8}\nDocumentation drifts because updating it is manual and unverified.\n::\n\n::evidence{id=\"evidence-docs-drift\" for=\"claim-docs-drift\"}\nThe last three incidents each involved a runbook step that no longer matched\nproduction behavior.\n::\n\n## Open Questions {id=\"open-questions\"}\n\n::open_question{id=\"q-release-cadence\"}\nShould the release cadence move from weekly to continuous?\n::\n\n## Agent Tasks {id=\"agent-tasks\"}\n\n::agent_task{id=\"task-refresh-architecture\" scope=\"docs/project.noma#architecture\" status=\"open\"}\nRe-verify the Architecture section against the current codebase once per week.\nPatch only blocks whose content is out of date, with one op per block.\n::\n",
  "patches/example-ops.json": "[\n  {\n    \"op\": \"update_attribute\",\n    \"id\": \"decision-0001\",\n    \"key\": \"status\",\n    \"value\": \"superseded\"\n  },\n  {\n    \"op\": \"replace_body\",\n    \"id\": \"q-release-cadence\",\n    \"content\": \"Should the release cadence move from weekly to continuous?\\nLeaning continuous after the deploy-pipeline hardening shipped.\"\n  }\n]\n",
  ".github/workflows/noma-ci.yml": "name: Noma docs CI\n\n# Two jobs:\n#   validate — every PR touching docs/ gets `noma check` + a rendered HTML\n#              artifact uploaded for review.\n#   proof    — when a PR also changes patches/proposed-ops.json, the ops are\n#              simulated against the BASE branch's document and the proof\n#              summary is posted as a PR comment. The job fails if the\n#              simulated post-patch document does not validate, so unsafe\n#              agent edits never reach the merge button.\n\non:\n  pull_request:\n    paths:\n      - 'docs/**'\n      - 'patches/**'\n\npermissions:\n  contents: read\n  pull-requests: write\n\njobs:\n  validate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Validate and render docs\n        uses: ferax564/noma@v__NOMA_VERSION__\n        with:\n          input: docs/project.noma\n          to: html\n          output: project.html\n          cli-package: '@ferax564/noma-cli@__NOMA_VERSION__'\n          artifact-name: rendered-docs\n\n  proof:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          ref: ${{ github.event.pull_request.base.sha }}\n          path: base\n      - uses: actions/checkout@v4\n        with:\n          path: head\n      - name: Check whether this PR proposes patch ops\n        id: ops\n        run: |\n          if [ -f head/patches/proposed-ops.json ]; then\n            cp head/patches/proposed-ops.json base/proposed-ops.json\n            echo \"present=true\" >> \"$GITHUB_OUTPUT\"\n          else\n            echo \"present=false\" >> \"$GITHUB_OUTPUT\"\n          fi\n      - name: Prove the patch is safe before merge\n        if: steps.ops.outputs.present == 'true'\n        uses: ferax564/noma@v__NOMA_VERSION__\n        with:\n          mode: proof\n          input: base/docs/project.noma\n          ops: base/proposed-ops.json\n          cli-package: '@ferax564/noma-cli@__NOMA_VERSION__'\n          comment-pr: 'true'\n          artifact-name: noma-proof\n",
  "AGENTS.md": "# Agent contract for this repository\n\nYou maintain the documents under `docs/`. They are Noma documents: structured\nplain text with stable block IDs. You edit them with **block-level patch\noperations**, never by rewriting files.\n\n## Iron rules\n\n1. **Never rewrite a `.noma` file wholesale.** Propose patch ops targeting\n   block IDs.\n2. **One op per logical change.** Small ops produce reviewable proofs.\n3. **Read before you write.** `noma ids docs/project.noma` lists every\n   addressable block. `noma render docs/project.noma --to llm` gives you the\n   document as deterministic context.\n4. **Prove before you propose.** Run\n   `noma proof docs/project.noma --ops <your-ops.json>` locally; only open a\n   PR if the proof passes.\n5. **Use `baseHash` when you can.** Hash the block you read\n   (`blockSourceHash`, or `hash` from the MCP server's `read_doc`) so your op\n   is rejected with `sha_mismatch` if a human edited the block after you read it.\n\n## How to propose an edit\n\n1. Write your ops to `patches/proposed-ops.json` as a JSON array, e.g.:\n   ```json\n   [\n     { \"op\": \"replace_body\", \"id\": \"overview\", \"content\": \"...\" },\n     { \"op\": \"update_attribute\", \"id\": \"decision-0001\", \"key\": \"status\", \"value\": \"superseded\" }\n   ]\n   ```\n2. Apply them so the doc and the ops stay in sync:\n   ```bash\n   noma patch docs/project.noma --ops patches/proposed-ops.json --inplace\n   noma check docs/project.noma\n   ```\n3. Commit both files on a branch and open a PR. CI re-simulates your ops\n   against `main` and posts the proof as a comment.\n\n## Available op types\n\n`replace_block`, `replace_body`, `update_heading`, `add_block`, `delete_block`,\n`move_block`, `update_attribute`, `remove_attribute`, `rename_id`,\n`add_comment`, `resolve_comment`, `add_change_request`, `add_footnote`,\n`add_endnote`, table ops (`update_table_cell`, `insert_table_row`, …) and\ndataset ops (`update_dataset_cell`, `insert_dataset_row`, …).\n\nSchema: `noma schema patch-op` (or `noma schema patch-transaction`).\n\n## MCP alternative\n\nIf you run tools over MCP, `@ferax564/noma-mcp-server` exposes `read_doc`\n(returns per-block `hash`), `list_ids`, `validate_doc`, and `patch_block`\n(accepts `base_hash`) over stdio:\n\n```bash\nnpx @ferax564/noma-mcp-server\n```\n",
  "README.md": "# Project docs\n\n**Docs your AI agents maintain — with proof, before merge.**\n\nThis template gives you a living knowledge base in [Noma](https://github.com/ferax564/noma):\nplain-text source that renders to polished HTML, exports deterministic LLM\ncontext, and lets agents edit **individual blocks by stable ID** instead of\nrewriting files. Every agent edit is simulated, validated, and posted to the\nPR as a proof comment before a human clicks merge.\n\n## The loop\n\n```txt\nagent reads block IDs  →  proposes patch ops  →  opens a PR\n        →  CI simulates the ops against main and posts a proof comment\n        →  human reviews the proof, merges\n        →  docs stay correct, diffs stay reviewable\n```\n\n## Try it in 5 minutes\n\n1. Scaffolded by `noma init --template docs-repo` (also available as the\n   [noma-docs-template](https://github.com/ferax564/noma-docs-template) GitHub template).\n2. Install the CLI: `npm install -g @ferax564/noma-cli`\n3. See the block IDs agents can target:\n   ```bash\n   noma ids docs/project.noma\n   ```\n4. Simulate a patch locally (nothing is written):\n   ```bash\n   noma proof docs/project.noma --ops patches/example-ops.json --out proof.html\n   open proof.html\n   ```\n5. Open a PR that adds `patches/proposed-ops.json` (copy `example-ops.json`)\n   — CI posts the proof summary as a PR comment and fails if the simulated\n   post-patch document is invalid.\n\n## What's in here\n\n| Path | Purpose |\n|---|---|\n| `docs/project.noma` | The knowledge base — sections, decisions, claims/evidence, agent tasks, all with stable block IDs |\n| `patches/example-ops.json` | A sample patch transaction agents can copy |\n| `.github/workflows/noma-ci.yml` | Validate + render on every docs PR; proof + PR comment when ops are proposed |\n| `AGENTS.md` | The contract your agents follow to edit these docs safely |\n\n## Why not Markdown?\n\nMarkdown has no stable block IDs, no validation, and no safe patch protocol —\nan agent \"updating one section\" rewrites the file and you diff-review the\nwhole thing. Noma documents validate in CI (broken references, claims without\nevidence, stale sections), and agents patch one block at a time with\noptimistic-concurrency `baseHash` preconditions, so concurrent human edits\nare detected per block.\n\nWant richer docs? Noma also renders PDF, DOCX (with native comments and\ntracked changes), multi-page sites, and budgeted LLM context from the same\nsource. See the [Noma repo](https://github.com/ferax564/noma) and\n[docs](https://ferax564.github.io/noma/).\n\n## Notes\n\n- Proof comments require a same-repo branch (fork PRs get a read-only token;\n  the proof still runs and the artifact uploads — only the comment is skipped).\n- The workflow pins the action and CLI to Noma __NOMA_VERSION__ for reproducible\n  CI. Bump `uses: ferax564/noma@v…` and `cli-package` together when you upgrade.\n",
  ".gitignore": "node_modules/\n*.html\n!.github/**\nproof.md\n",
};

/** Files to write, keyed by repo-relative path. A semver `version` pins the Action and CLI; anything else falls back to `@main` / `@latest`. */
export function docsRepoTemplateFiles(version: string): Record<string, string> {
  const pinned = /^\d+\.\d+\.\d+/.test(version);
  const result: Record<string, string> = {};
  for (const [path, content] of Object.entries(FILES)) {
    result[path] = pinned
      ? content.split(PIN).join(version)
      : content.split(`ferax564/noma@v${PIN}`).join("ferax564/noma@main").split(`@ferax564/noma-cli@${PIN}`).join("@ferax564/noma-cli@latest").split(PIN).join("latest");
  }
  return result;
}
